### ISSUE TITLE
hard to close user profile drop down menu

### ISSUE THREAD

**Issue by Mullefa** [guardian/membership-frontend#551]
At the url `http://www.theguardian.com/membership#`, the drop down menu I get from clicking on my user profile (top left), can only be closed by re-clicking on my member profile (as opposed to anywhere off the drop down menu). I'm using Google Chrome on a MacBook.

**Comment by davidrapson** [comment]
Hi @Mullefa , thanks for raising this. I've raised this issue again at https://github.com/guardian/frontend/issues/9255 as it looks like your issue occurs on theguardian.com so have passed it on to that team.
