### ISSUE TITLE
Broken encoding in user name on front page

### ISSUE THREAD

**Issue by theefer** [guardian/membership-frontend#744]
![image](https://cloud.githubusercontent.com/assets/36964/9721615/eb9d7d4a-5595-11e5-8c0b-45fe1c61ce4f.png)

I have traced the bug down to the membership cookie, which seems to contain a base-64 encoded spurious string:

```
$ echo ey[etc..] | base64 -d
{"userId":"___","regNumber":"___","firstName":"Sbase64: invalid input
```

My suspicion is that the [this line](https://github.com/guardian/membership-frontend/blob/eb49e2d8d2f9ea09add0c451f90aa94da61bf5bd/frontend/app/utils/GuMemCookie.scala#L9) should specify the UTF-8 encoding explicitly (`s.getBytes("UTF-8")`).

We recently fixed a similar issue in panda, see [related code](https://github.com/guardian/pan-domain-authentication/blob/e4491df4ea800d0adf9b9eba1f0b20a5302f7d53/pan-domain-auth-verification/src/main/scala/com/gu/pandomainauth/service/CookieUtils.scala#L38).

**Comment by davidrapson** [comment]
Thanks seb, just raised a PR with this fix https://github.com/guardian/membership-frontend/pull/745

Oddly I don't get the encoding issue on Mac or Windows, using a test user with Sébastien seems to get encoded/decoded correctly in those environments.

````
{"userId":"____","regNumber":"____","firstName":"Sébastien","tier":"Supporter","isPaidTier":true,"joinDate":____}%
```

However @rtyley *has* repeated the issue on linux so have asked him to give this fix a quick check.

**Comment by theefer** [comment]
It may be due to the behaviour of `String.getBytes` on different OSes (or JVM versions) and whether a default encoding is used?

**Comment by davidrapson** [comment]
Seems like that's probably the case. http://docs.oracle.com/javase/7/docs/api/java/lang/String.html#getBytes() says "platform's default charset" with a fallback to `ISO-8859-1`. Which explains why we're seeing different results across environments. Sounds like your change should sort it.

**Comment by rtyley** [comment]
> Oddly I don't get the encoding issue on Mac or Windows

I'm guessing this was running membership locally @davidrapson ? Are you able to recreate the issue when hitting membership.theguardian.com ?

**Comment by davidrapson** [comment]
@rtyley Had to futz around with test users a bit to repeat it as you need a tier to see the message, but yep can repeat it. Looks like is the default environment encoding then.

![screen shot 2015-09-08 at 12 11 57](https://cloud.githubusercontent.com/assets/123386/9733402/d604418e-5622-11e5-9757-e5146051061f.png)

**Comment by davidrapson** [comment]
Looks like that changed fixed it, thanks for the fix @theefer 

![screen shot 2015-09-08 at 12 44 58](https://cloud.githubusercontent.com/assets/123386/9733991/a1cf94f4-5627-11e5-8c52-a2a149089b55.png)

@theefer Would you mind double checking?

Shame though, I always liked the name S?bastien
